### ISSUE TITLE
DS3 inverters

### ISSUE THREAD

**Issue by carmelo42** [patience4711/RPI-APS-inverters#1]
Hello ! 
Do you know if it is possible to read DS3 inverters ?
I have pi zero, and CC2530 device, and I'm available to do some testing :)

**Comment by patience4711** [comment]
@carmelo42 
I am sure it's possible, ask this on https://github.com/Koenkk/zigbee2mqtt/issues/4221
To find out how, you need to find someone with an official ECU and DS3 inverters who is prepared to sniff the zigbee trafic. 
I can't help you with this.

**Comment by carmelo42** [comment]
Ok, thanks :)
