### ISSUE TITLE
SD card almost full !

### ISSUE THREAD

**Issue by defaliz** [patience4711/RPI-APS-inverters#104]
Hi,
my sd card is almost full
/dev/root       4.1G  3.9G  198M  96% /

what kind of files could be removed ?
best regards
Alain

**Comment by Hansiart2** [comment]
You could look in var log and its subdirectories. All files with a .gz extension can be removed. Most likely apache2 has many logfiles.

BTW this seems a small card to me, (4Gb) is that correct? If not, did you expand the filesystem?

**Comment by defaliz** [comment]
Thank Hansiart
you're right, it's a small capacity card...
i'll bought and another one do a copy...
regards
