### ISSUE TITLE
Uploaded photo not showed - Deleted photo not deleted (RPI-ECU-v3_9)

### ISSUE THREAD

**Issue by autourdupc** [patience4711/RPI-APS-inverters#107]
Hello.

Using RPI-ECU-v3_9

I'm trying to upload a photo.
Tested on Firefox and Edge... Not working.
Strangely, on Firefox, a pop-up asks for a new upload. Whatever your choice is, it is not good. See below.
The photo is not uploaded while the message says its okay.

When trying to deleted the exiting photo (your photo), its says its okay, but not. Your photo remains.

Here is an upload sequence...
![Photo1](https://github.com/patience4711/RPI-APS-inverters/assets/152384092/e3c5b496-af17-48e6-a244-e926d145a1fb)

![Photo2](https://github.com/patience4711/RPI-APS-inverters/assets/152384092/f47866fc-7e8b-4cab-a434-04ddf1e5471a)

![Photo3](https://github.com/patience4711/RPI-APS-inverters/assets/152384092/fa1cf230-8c4f-470e-89cf-946060ced56c)

![Photo4](https://github.com/patience4711/RPI-APS-inverters/assets/152384092/40122e33-751c-4208-9748-8c077fa8ad55)

![Photo5](https://github.com/patience4711/RPI-APS-inverters/assets/152384092/e9f984e2-f3b8-422a-8a1a-1da04c167c44)

Best regards,

**Comment by patience4711** [comment]
@autourdupc  did you see the help button? Useually emtying the browsercache will do the trick,

**Comment by autourdupc** [comment]
@patience4711 
You are the king.
Using a second computer provide the right photo after some times...
