### ISSUE TITLE
Update 3.10

### ISSUE THREAD

**Issue by jmguilbert** [patience4711/RPI-APS-inverters#109]
Hello Patience
Thé link for download ecu_swupdate-v3_10.tar is dead.
Can you repear it ?
Thanks. JM.

**Comment by patience4711** [comment]
This link is not active because i didn't have time to test it. I am currently moving the whole system to the latest debian version "bookworm" so i have no spare system to test with.  I uploaded it however so if you need it you can find it in the files.
