### ISSUE TITLE
About CC2531 zigbee dongle

### ISSUE THREAD

**Issue by defaliz** [patience4711/RPI-APS-inverters#110]
Hello,
can we use installed zigbee2mqtt to use cc2531 dongle for detecting connected other device ?
regards (thanks for 3_10 version link)

**Comment by patience4711** [comment]
No sure what your question is, I know nothing about zigbee2mqtt. The cc2531 we use in this project has firmware that is dedicated to the AP invertes and won't work with other devices.

**Comment by defaliz** [comment]
ok, thanks
if the firmware is dedicated to zigbee APS protocol so it won't work on other zigbee devices...
regards
