### ISSUE TITLE
About home page

### ISSUE THREAD

**Issue by defaliz** [patience4711/RPI-APS-inverters#111]
Hi,
It's the  first time i see the red color around the frame on the home page...
What does it means ?
Regards
![Screenshot_20240314-105546376_1](https://github.com/patience4711/RPI-APS-inverters/assets/41428343/4b6d3a94-fc69-41d1-9e8c-1bc67ec4baea)

**Comment by patience4711** [comment]
It is a fun feature, a visual indication that energy is delivered.  The more energy is yielded, the more red it wil be. So it will be gone at the end of the day.

**Comment by defaliz** [comment]
Excellent ! Very good Idea...
Thanks 
Alain
