### ISSUE TITLE
using mosquitto in home assistant

### ISSUE THREAD

**Issue by defaliz** [patience4711/RPI-APS-inverters#112]
Hi,
i'm using mqtt to create sensors in Home Assistant
i have datas in mqtt like this : 
{"serial":"xxxxxxxx","acv":232.6,"freq":50.0,"temp":15.1,"pwr":[21.4,20.6],"en":[41.6,40.6],"totalpwr":42.0,"totalen":82.2}
with differents lines and serial, because i've 3 inverters
but how can i discriminate datas between my 3 inverters ?
thank a lot
here is a declaration sensor in my home assistant : 
mqtt:
  sensor:
#power  
    - name: inv0 pwr1
      unique_id: inv0 pwr1
      state_topic: "rpiecu/out"
      json_attributes_topic: "rpiecu/out"
      value_template: '{{ value_json.pwr[0] }}'
      unit_of_measurement: 'W'
      
    - name: inv0 pwr2
      unique_id: inv0 pwr2
      state_topic: "rpiecu/out"
      json_attributes_topic: "rpiecu/out"
      value_template: '{{ value_json.pwr[1] }}'
      unit_of_measurement: 'W'

**Comment by defaliz** [comment]
here is result in mqtt explorer, 3 lines (first none panel is connected)
11:45:27
{"serial":"703000518414","acv":0,"freq":0,"temp":0,"pwr":[0,0],"en":[,],"totalpwr":0,"totalen":0}
11:45:24
{"serial":"703000557318","acv":238.7,"freq":50.0,"temp":28.6,"pwr":[255.2,246.5],"en":[416.4,392.7],"totalpwr":501.7,"totalen":809.0}
11:45:20
{"serial":"703000071646","acv":238.7,"freq":50.0,"temp":31.3,"pwr":[189.7,331.8],"en":[340.0,565.4],"totalpwr":521.5,"totalen":905.4}
is there a way to create 3 differents sensors in Home Assistant... ?
regards

**Comment by patience4711** [comment]
I am not really familiair with Home Assistent but i think that each sensor has its own mqtt topic. <br>
You can have different topics for each inverter in the RPI-ECU. First you go to the inverter settings and fillup an IDX number for each inverter (p.e. 111, 222, 333 if you have 3 inverters). <br>Now, in mqtt settings, put a slash ("/") behind the send topic .<br>Now the idx of the inverter will be added automatically to the sendtopic. P.e. if you have an inverter with IDX **123**, and a sendtopic **your/topic/** the mosquito message goes to **your/topic/123**.
This way you can have a separate topic for each inverter.

**Comment by defaliz** [comment]
thanks again !
it's exactly what i want and that works like a charm...
regards
Alain

**Comment by autourdupc** [comment]
@defaliz 

Hello defaliz.
I just start with HA, and try to link RPI-ECU with HA via MQTT.

I really need help to get the data... Could you explain to me ?
I just installed MQTT in HA, then never be able to get data from RPI-ECU.
![image](https://github.com/user-attachments/assets/5437501e-d096-4543-93b5-f2d0fcbd7f9b)

Thanks in advance.

**Comment by defaliz** [comment]
Hi autourdupc
do you create IDX for each inverters and mosquitto host and port in rpiecu interface ?
after that you must create entries in a yaml file, and you should see sensors in HA
sorry but, i'm far from my home, and for now there is a big storm in Normandy and problem on enedis power...
so no remote access... as soon as power is establish, i'll send you my scripts
regards

**Comment by autourdupc** [comment]
Hello.

I created IDX for each inverters
Concerning mosquitto, here are the settings
![image](https://github.com/user-attachments/assets/690f5a40-99c7-49c8-8504-2573593a5e33)

**Comment by defaliz** [comment]
i think you must not add http for address mqtt, because this is not the protocol
simply the ip address
here is my conf, in ecu_data/mqttConfig.json file

{"enabled":1,"retain":0,"address":"10.3.141.16","port":1883,"intopic":"rpiecu/in/","outtopic":"rpiecu/out/","auth":1,"username":"mqtt","password":"mqtt","format":2}

**Comment by defaliz** [comment]
hello,
here an example of my mqtt.yaml for a sensor inv0

sensor:                                                                                                                         
    # données RPIECU inv0                                                                                                      
    - name: inv0 temp0                                                                                                          
      unique_id: inv0 temp0                                                                                                     
      state_topic: "rpiecu/out/000"                                                                                             
      json_attributes_topic: "rpiecu/out/000"                                                                                   
      value_template: '{{ value_json.temp }}'                                                                                   
      unit_of_measurement: 'C..'

**Comment by autourdupc** [comment]
@defaliz 
I love creating programs... But here, HA is very strange !
Even trying to understand how it works, I'm unable to get my sensor running without error... I find HA very very hard to use !!!

**Comment by defaliz** [comment]
You're right, i've spend lot of hours to understand HA sensors concept
for me i've create mqtt.yaml file (declare it in configuration.yaml file)
and first sensor power declaration is like that (inverter 0 and first panel) :
sensor:                                                                                                                                                                                                                    
    - name: inv0 pwr1                                                                                                           
      unique_id: inv0 pwr1                                                                                                      
      state_topic: "rpiecu/out/000"                                                                                             
      json_attributes_topic: "rpiecu/out/000"                                                                                   
      value_template: '{{ value_json.pwr[0] }}'                                                                                 
      unit_of_measurement: 'W'

so after that you can see your sensor in HA entities
![image](https://github.com/user-attachments/assets/7ab3f54e-b13a-4785-a15f-0b326275e5d7)

before you must configure rpiecu, mosquitto settings
![image](https://github.com/user-attachments/assets/002722bf-9037-46d5-9899-925f8450de16)

**Comment by autourdupc** [comment]
Thanks for the help...
I was able to get tests messages from RPI-ECU.
Today, no messages anymore, nor new sensor appeared despite my settings... Very boring !

**Comment by defaliz** [comment]
hum...
connecting with ssh on rpiecu can you publish and subscribe on HA with 
mosquitto_pub and mosquitto_pub ? 
mosquitto_sub -v -h ip_HA  -u username -P password -t '#'

**Comment by autourdupc** [comment]
Using test button I get the output on a new page...
running script mqttTest...
the value of auth = 1
the value of username = MQTT_User
the value of password = mqtt
testcommand = mosquitto_pub -h 192.168.20.241 -u MQTT_User -P mqtt -t rpiecu/out/ -m 'authenticated hello from rpi ecu'
mosquitto test runned..
HTTP:1/1 200 OK

**Comment by defaliz** [comment]
i think you found a bug...
further to test, i've used mqtt explorer to see messages...
and there are only my last test from rpiecu, and no history from inverters
BUT, my sensors rpiecu on HA are all available ! i don't understand...
last week i used version 3_10 and i don't verify...
maybe a problem with version 4...
we must wait for tomorow having new solar production...
![image](https://github.com/user-attachments/assets/2bf29cce-915b-4d8a-b83b-c29e62ab4c7b)

**Comment by defaliz** [comment]
faudra ouvrir un case demain si ça persiste...

**Comment by autourdupc** [comment]
Hum...
I was not aware about thoses tools...
Once installed, I can see that RPIECU is working
![image](https://github.com/user-attachments/assets/7449114c-a996-4cf3-a9a3-e14d692ad9e4)

**Comment by defaliz** [comment]
hello,
strange i don't know why but for now on mine i can only seeing mqtt test
![image](https://github.com/user-attachments/assets/2f3b64ac-3415-4927-a0f4-18654eeca6a7)
you are on RPI-ECU-v4_3 ?
can you please send me contain of /var/www/ecu_data/mqttConfig.json
merci

**Comment by autourdupc** [comment]
I can get values from RPIECU, only in MQTT Explorer
Nothing here...
![image](https://github.com/user-attachments/assets/22f7b4af-8fc3-4789-b7f0-cdd7abcc730c)

Here is my /var/www/ecu_data/mqttConfig.json file content
{"enabled":1,"retain":0,"address":"192.168.20.241","port":1883,"intopic":"rpiecu/in","outtopic":"rpiecu/out","auth":1,"username":"MQTT_User","password":"mqtt","format":2}

**Comment by defaliz** [comment]
thank
in HA i don't use configuration of mqtt
![image](https://github.com/user-attachments/assets/d265fd34-2a8b-4c0f-9717-4111e5afdee6)
i only create sensor in mqtt.yaml, restart HA and tha't all

**Comment by defaliz** [comment]
so, i've launch manually
/usr/lib/cgi-bin/ecu/autoPoll.pl

and now i've good message from rpiecu
![image](https://github.com/user-attachments/assets/c1c55dbe-a42f-46e8-ab25-48555cf8a844)
and here is datas in HA
![image](https://github.com/user-attachments/assets/c7622caa-4ef9-4855-a216-a9508e5fd961)

do you create your sensors in configuration.yaml or in a separate file ?

**Comment by autourdupc** [comment]
I think you are right...
There is no auto refresh after you lauch a "Test" in RPIECU
![image](https://github.com/user-attachments/assets/88a40e49-6afb-4e49-9c97-0a24016fc024)

**Comment by autourdupc** [comment]
> do you create your sensors in configuration.yaml or in a separate file ?

In a separate file... But I think I made a mistake in the folder tree... I need to check
-> Cheked and good ! 
I created a folder named "sensors" where i put my rpiecu.yaml file
I linked this file from "configuration.yaml" like this
![image](https://github.com/user-attachments/assets/66dab1f9-0f03-4f5f-a5fd-68494459dd28)

And my rpiecu.yaml is like this (these are your settings)
![image](https://github.com/user-attachments/assets/f2698890-8f1e-403b-bb91-5268a93e97c7)

Now I got data from rpiecu in the MQTT Explorer, but no more.

What is missing now to get the values visible in the main page ?
Where should I find my sensor ?

**Comment by defaliz** [comment]
first you can try to put your rpiecu.yaml in same folder than configuration.yaml
sensors w'll be seing in mqtt integration
![image](https://github.com/user-attachments/assets/288dc4e4-5a07-42ef-9dfc-eba055376358)
have a look to your logs in système, journaux
![image](https://github.com/user-attachments/assets/e41e4494-a3b2-4cd5-b8e7-9a0b7516cb33)

**Comment by autourdupc** [comment]
The MQTT Broker logs...
![image](https://github.com/user-attachments/assets/bed0a313-97b5-462b-bd9b-95cd3f2233a2)

**Comment by defaliz** [comment]
You have same logs as me for mqtt, so maybe problem in sensors creation...
you have to restart HA each time you manually modify a yaml file, if there is a format problem in the yaml file HA you'll know it...
i've read autoPoll.pl (extract in bottom of message ) and there is no poll of mqtt during nighttime and if polling of inverter failed (i understand why i hav'nt no message yesterday :) )
I post you a message on your issue "https://github.com/patience4711/RPI-APS-inverters/issues/129" because there is something strange...

 __my$autopollCmd = "sudo /usr/lib/cgi-bin/ecu/inverterPoll.cgi $_";
          print "autopollCmd = $autopollCmd\n<br>";
          my $result = system($autopollCmd);
          print "result = $result \n<br>"; # result = 0 or 256 -1

          # if result = 0 the polling succeeded then we should mqtt
             if($result == 0)
             {
                 my $mqttCommand = "/usr/lib/cgi-bin/ecu/sendMqtt.cgi $_";
                 system($mqttCommand);
             }__

**Comment by autourdupc** [comment]
I did not check on existing files in RPIECU... I do not have time to makes my HA running, do my job (hey, need also to earn money !), debug (if needed ???) RPIECU... 
But I think I got it after pressing "Test" on RPIECU... It seems to stop / fail polling sometimes !

**Comment by defaliz** [comment]
Yes mine failed checking zigbee device very often, and then no polling at all ..
I've used rpiecu.3_4 version for 2 years without this problems...
