### ISSUE TITLE
Inverter (inv0) available but Error Message "currently no inverters registered"

### ISSUE THREAD

**Issue by kentbrock** [patience4711/RPI-APS-inverters#113]
firmware version = RPI-ECU-v3_10 

I got the message - to be honest since a long time and even older firmware versions:  "currently no inverters registered".

There is an inverter registred Inv 0 and its working. 

![grafik](https://github.com/patience4711/RPI-APS-inverters/assets/58900372/d03be52b-3744-4966-ab5e-92ab2bb1c2b1)

![grafik](https://github.com/patience4711/RPI-APS-inverters/assets/58900372/093a47fc-c613-4d48-9ce8-427ff35241a5)

this is a little bit an issue due to the fact, that I´m not able to perform statistics:

![grafik](https://github.com/patience4711/RPI-APS-inverters/assets/58900372/d5a983c3-e0a5-410b-b508-afc82f16fc6b)

Is there a way to fix this?

Thanks

**Comment by patience4711** [comment]
If you can ssh into the raspberry you can check /var/www/ecu-data/inverterCount.txt. Likely there is a value of 0 in the file where it should be 1 (just a 1, no spaces, empty lines or what so ever).
