### ISSUE TITLE
sometimes no datas displayed...

### ISSUE THREAD

**Issue by defaliz** [patience4711/RPI-APS-inverters#114]
hi,
i use 3_10 version... sometimes there are no datas on home page... if i reboot my pizero datas are displaying...
do you know why ?
best regards
![image](https://github.com/patience4711/RPI-APS-inverters/assets/41428343/4daad3e2-3b18-4f22-b043-5fc54edb2c9a)

**Comment by patience4711** [comment]
Sorry, no. If the polling fails for some reasons the values are null. When this happens i suggest that you make use of the debug options to get a better picture of what happened here.
Btw what is that auquemesnil, the actual time? Something you programmed yourself?

**Comment by defaliz** [comment]
thanks for the answer
I haven't had the problem for 15 days...
it's certainly a problem with my pi zero...
regards
