### ISSUE TITLE
Chart for all inverters

### ISSUE THREAD

**Issue by defaliz** [patience4711/RPI-APS-inverters#116]
Hi
i'm wondering why is there no charts for totals values ( power and energy) like for inverters ?
maybe on a next version  :-)
regards
![image](https://github.com/patience4711/RPI-APS-inverters/assets/41428343/aea1425d-4436-4cbb-b6f5-0c05be741bf3)

**Comment by patience4711** [comment]
That graph will look the same as all individual graphs so it yields nothing new. It would take too much time to query all the inverter databases and totalize all the values. So no, there are no plans to implement that.
Maybe your domoticz software can do it.

**Comment by autourdupc** [comment]
Hello @defaliz...

Maybe you could try this one I've just created... 
https://github.com/patience4711/RPI-APS-inverters/issues/129
