### ISSUE TITLE
version 3_10 no chart for chart_pe.php page

### ISSUE THREAD

**Issue by defaliz** [patience4711/RPI-APS-inverters#123]
Hi
thanks for new version 4
i'll try soon...
but for now i've a problem with version 3.10, i've no chart on chart_pe.php
i've seen that the script read /var/www/ecu_data/chartDate.txt but this file does not exist !
how  and when is it create ?
thanks for help
alain

**Comment by defaliz** [comment]
Solved...
that was a problem about space on disk... i've change SD card and now it's good...
On the version 4_1 are there some news features or it's only because of linux kernel ?
regards

**Comment by patience4711** [comment]
It is mainly a linux update. No really new features but the performance of the webinterfaces on telephones is better.

**Comment by defaliz** [comment]
thanks a lot...

**Comment by defaliz** [comment]
Hi,
sorry to re-open this post... but the problem persist...
yesterday (19/08) i had chart on this page chartjs/chart_pe.php?page=0&inv=1
but nothing for the others days... today and before yesterday...
how can i investigate furthermore ?
![image](https://github.com/user-attachments/assets/ec72a665-454c-47aa-a3b6-c4a50106c0c3)

regards

**Comment by defaliz** [comment]
ok, sorry, the problem was that influxd was stopped... i don't know why...
sometimes it does...
it's OK know
regards
