### ISSUE TITLE
2_0 still says in firmware 1_5

### ISSUE THREAD

**Issue by kentbrock** [patience4711/RPI-APS-inverters#23]
I just installed the 2.0 RPI Version. Everything seems to work. Restoring Backup also! Great work so far. I´ve seen some small issues. In the Info Page there is still version 1.5 displayed and the the photo upload does not work. I renamed the photo to ecu_photo.jpg. Do I have to resize the photo?

My Hardware: RPI 2 with Edimax WIFI stick.

**Comment by patience4711** [comment]
Yes your backup restored the old version nr.  back. Something i overlooked. Did you click the help button? What does the debug info say?

**Comment by kentbrock** [comment]
Sorry, I have not seen the Help button. :-) The size of the picture was to big. Everything else is working fine until now. Great good work - thanks alot. I would still like to modify the ntp server? Can I do it by my own in one specific file?

**Comment by patience4711** [comment]
Oke, pfff, glad that it works, broadly speaking... 
For the version you can edit /var/www/ecu_data/swVersion.txt, in the next update it will be fixed.
The timekeeping is a typical linux thing, current os: raspbian-buster. You can find out yourself.
Good luck

**Comment by kentbrock** [comment]
Perfect :-)

I´ve changed the SW Version and the time server. 

To change the time server I´ve done the following steps:

`nano /etc/systemd/timesyncd.conf` uncomment lines and change to the desired time server
`systemctl enable systemd-timesyncd`
`systemctl start systemd-timesyncd`

after reboot I´ve check the sync with 
`timedatectl `
and more detailed
`systemctl status systemd-timesyncd.service`

P.S.: I noticed something else that I can't tell if it's because of my browser.
When updating to V1_5 I could download the backup file only with Chrome - not with Firefox. With V2_0 the download of the backup file did not work with Chrome, but with Firefox.

**Comment by patience4711** [comment]
Yes, that is browser specific, With chrome sometimes i didn't see the download. But i hope that we do not need that anymore,  and that all future sw changes that can be handled by the sofware update script.
