### ISSUE TITLE
cc25 firmware

### ISSUE THREAD

**Issue by mamaretti** [patience4711/RPI-APS-inverters#27]
Hi patience4711

can you please share the firmware for the cc25xx module?

can't find the post of the correct firmware
https://github.com/Koenkk/zigbee2mqtt/issues/4221

i want to use a ByteE18 MS1PA2 but its not working with RPI or ESP so far.

is there any way to check the version of Zigbee module via ESP-Console?

would be great if you can help me.

can u share your binary of ECU right here in Github? 

why you use 1drv.ms?

thx

**Comment by iLeopod** [comment]
https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.0.x/bin

**Comment by patience4711** [comment]
You should note that the used firmware here is dedicated to this project and the cc25xx, developped by @kadszol. 
It is included in this package:
https://github.com/Koenkk/zigbee2mqtt/files/6797510/discord-11-7-2021.zip 

With the esp-ecu you can send zigbee commands read Z-Stack.Monitor.and.Test.API.pdf to find out what to send for version info.  Wont work with the ByteE18 MS1PA2 i guess.

Why i use onedrive? It's free and i like it.
There is a binary here in github at the esp-ecu repo

**Comment by mamaretti** [comment]
thx for the link!

**Comment by mamaretti** [comment]
Hi patience4711

so I flashed the E18 MS1PA2 with CC2530ZNP-cc2591-with-SBL.hex and I'm still won't get data from inverter.
i have a second Hardware with Z-001 and ESP which work ok with our latest version 8 Beta5.

poll gives me 

polling answer FE0164010064
no AF_DATA_CONFIRM
polling failed 11

health 
inMessage = FE02610179071C rc = 7
ping ok
inMessage = FE0E670000FFFF80971B01A3D8000007090011 rc = 19

im not sure what's wrong here. can you help me with that?
thx

**Comment by mamaretti** [comment]
its a distance problem 
E18 MS1PA2 is working when I go closer to inverter
