### ISSUE TITLE
RPI-ECU-v2_1 without WiFi?

### ISSUE THREAD

**Issue by ToxSox** [patience4711/RPI-APS-inverters#29]
In the documentation it was written that the software also runs on a "goodold raspi 1".
I have a Raspberry Pi 1B and would work with it right now. However, the device has no WiFi and I would connect it via Ethernet.
Will this work or will the system hang because of the lack of WiFi?

**Comment by ToxSox** [comment]
The system starts but doesnt get an ip adress on eth0.

**Comment by patience4711** [comment]
@ToxSox 
Just checked and this works:
If you can ssh into the raspberry, add this to /etc/network/interfaces right after iface lo inet loopback:

**auto eth0
allow-hotplug eth0
iface eth0 inet dhcp**  

Disable the service wificheck
#systemctl disable wificheck

#reboot

**Comment by rasor89** [comment]
@patience4711 How can I make an SSH connection with raspberry without IP?
