### ISSUE TITLE
 inverters do not communicate well in cloudy days

### ISSUE THREAD

**Issue by b31k** [patience4711/RPI-APS-inverters#31]
Good afternoon
I have a little problem when I have a cloudy day, for example clouds appear and are removed, the inverters do not communicate well.
However, if it is a sunny day from early in the morning it works fine all the time.

EVENTS JOURNAL

2022-03-22 01:00:00 running midNight.cgi
00:00:03 midNight.cgi moved energy total into db invEnergy
midNight: removed data files
sun.py : calculated sunrise / sunset
00:04:03 checking zb system failed, need start (6700) command
00:04:17 checking zb system running ok
07:00:06 woke up from sleep, goodmorning!
going to perform the morning ritual
invdataNull.cgi: wrote a new /ramdisk/invData0 with null values
invdataNull.cgi: wrote a new /ramdisk/invData1 with null values
invdataNull.cgi: wrote a new /ramdisk/invData2 with null values
Wrote 0 in database invData,
1st poll in 5 min, now exit
07:05:07 polled inv 0 error 10 AF_DATA_REQ fail
invdataNull.cgi: set values to null except
for totalen and time in /ramdisk/invData0
07:05:08 polled inv 1 error 10 AF_DATA_REQ fail
invdataNull.cgi: set values to null except
for totalen and time in /ramdisk/invData1
07:05:10 polled inv 2 error 10 AF_DATA_REQ fail
invdataNull.cgi: set values to null except
for totalen and time in /ramdisk/invData2
07:10:07 polled inv 0 error 10 AF_DATA_REQ fail
invdataNull.cgi: set values to null except
for totalen and time in /ramdisk/invData0
07:10:09 polled inv 1 error 10 AF_DATA_REQ fail
invdataNull.cgi: set values to null except
for totalen and time in /ramdisk/invData1
07:10:10 polled inv 2 error 10 AF_DATA_REQ fail
invdataNull.cgi: set values to null except
for totalen and time in /ramdisk/invData2
07:15:07 polled inv 0 error 10 AF_DATA_REQ fail
invdataNull.cgi: set values to null except
for totalen and time in /ramdisk/invData0
07:15:08 polled inv 1 error 10 AF_DATA_REQ fail
invdataNull.cgi: set values to null except
for totalen and time in /ramdisk/invData1

....
....
![solar](https://user-images.githubusercontent.com/23245507/159526535-2709e94d-349c-4d95-b830-94a63fa1fbfe.jpg)
![inv](https://user-images.githubusercontent.com/23245507/159526563-854f6d50-0236-4fa4-b507-55f41ee55a63.jpg)

**And other day with similar condition, run well!**

<img width="1280" alt="Screen Shot 2022-03-23 at 17 36 00" src="https://user-images.githubusercontent.com/23245507/159750376-ea3eb24f-34ea-4b2e-8b7b-a368616c43d6.png">
<img width="1280" alt="Screen Shot 2022-03-23 at 17 36 54" src="https://user-images.githubusercontent.com/23245507/159750412-41ea8141-d265-4a64-bd4c-9f87a02dca47.png">
run well
EVENTS JOURNAL

16:34:42 checking zb system failed, need start (6700) command
16:34:58 checking zb system running ok
16:38:13 polled inv 0 the penultimate total energy value was 0
16:38:13 polled inv 0 ts: 34197 pw: 188.1
16:38:15 polled inv 1 the penultimate total energy value was 0
16:38:16 polled inv 1 ts: 34281 pw: 219.1
16:38:17 polled inv 2 the penultimate total energy value was 0
...
17:15:07 polled inv 0 ts: 299 pw: 154.7
17:15:09 polled inv 1 ts: 299 pw: 179.6
17:15:11 polled inv 2 ts: 299 pw: 176.6
17:20:07 polled inv 0 ts: 300 pw: 167.1
17:20:09 polled inv 1 ts: 300 pw: 192.7
17:20:11 polled inv 2 ts: 299 pw: 189.1
17:25:07 polled inv 0 ts: 300 pw: 162.5
17:25:09 polled inv 1 error 11 AF_DATA_CONFIRM fail
invdataNull.cgi: set values to null except
for totalen and time in /ramdisk/invData1
17:25:11 polled inv 2 ts: 300 pw: 183.2
17:30:07 polled inv 0 ts: 300 pw: 128.7
17:30:09 polled inv 1 error 11 AF_DATA_CONFIRM fail
invdataNull.cgi: set values to null except
for totalen and time in /ramdisk/invData1
17:30:11 polled inv 2 ts: 300 pw: 147.7
17:35:07 polled inv 0 ts: 300 pw: 92.5
17:35:09 polled inv 1 ts: 900 pw: 148.4
17:35:11 polled inv 2 ts: 300 pw: 106.6
...
...

**In chart can see the days comunication with inverters failed.**
<img width="1280" alt="Screen Shot 2022-03-23 at 17 40 47" src="https://user-images.githubusercontent.com/23245507/159751478-35191cc8-4221-4228-9fd4-b88d59e28a7e.png">

**Comment by patience4711** [comment]
@b31k Sorry for my delayed reaction, too busy with other problems. Well i cannot recognize this problem, my raspberry has runned for 38 days without missing one single poll. So i couldn't say what could be the cause of this. From your chart i conclude that the communication failed during the whole day. Never seen that. What zigbee module?

**Comment by b31k** [comment]
I try fixed added, 
**0 */1 * * * ( /usr/lib/cgi-bin/ecu/startCoordinator.pl normal=1 )** to crontab.
why i saw this
14:06:03 checking zb system failed, need start (6700) command
14:06:18 checking zb system failed, no answer on serial
14:06:31 checking zb system running ok
14:06:58 polled inv 0 ts: 411 pw: 915.7
14:07:00 polled inv 1 ts: 411 pw: 1024.5
14:07:02 polled inv 2 ts: 411 pw: 1025.3
...
