### ISSUE TITLE
wrong daily energy value in chart

### ISSUE THREAD

**Issue by patience4711** [patience4711/RPI-APS-inverters#32]
Something when wrong with the dts transition 27 march, probably due to the fact that the database works with uts time. 
It seems that the daily energy value is doubled. 

I could not find a systematically reason for this.

In a new software upgrade i added a utility that we can use to edit the energy value for an inverter on a certain day. Now we can correct eventually wrong or missing data.

**Comment by kentbrock** [comment]
Same happend for me. But your new edit tool works pretty good.
