### ISSUE TITLE
Pairing with DS3-L successful

### ISSUE THREAD

**Issue by 21-Jailbraik-21** [patience4711/RPI-APS-inverters#33]
Hello, got it thanks to the guys: https://github.com/Koenkk/zigbee2mqtt/issues/4221
Pairing a DS3-L.

Unfortunately, the values ​​that are displayed are not good and are not correct.

Has anyone tried the same thing and can help?

it would be great if we could get the ds3 to work

https://github.com/Koenkk/zigbee2mqtt/issues/4221#issuecomment-1083183799

**Comment by patience4711** [comment]
@21-Jailbraik-21  Thanks for your intrest in my software. Did you read somewhere that this project would support a DS3? We are working to get it right for the esp project, when this works i can port it to the rpi. 
For more information please read up at https://github.com/patience4711/read-APSystems-YC600-QS1-DS3/issues/19
