### ISSUE TITLE
is it possible to control the inverter with this???

### ISSUE THREAD

**Issue by hschraep** [patience4711/RPI-APS-inverters#37]
Hello,
find you project and its greate. Intresting would be if it is also possible to send commands to the inverter to let control him.
One option would be to let reduce the power of the inverter to let charge with the not needed power a battery. Would be great if this would be possible. rgds zizyfuzz

**Comment by patience4711** [comment]
@hschraep The RPI-ECU has a console that allows the user to send zigbee commands. So in theory this is possible, you only have to find out what capabilities the inverter has and what the zigbee commands are. Currently nobody knows.

**Comment by hschraep** [comment]
Ok, sounds great, i think if i get a APsystems DS3-S i will build this and i will try to figure out more, thanks for the informations.

**Comment by hschraep** [comment]
btw, all DS3 are compatible to your FW? DS3-S and also the DS3L?

**Comment by patience4711** [comment]
@hschraep  I think so but i can not test this, i don't own a DS type inverter.
