### ISSUE TITLE
SONOFF ZigBee 3.0 USB Dongle Plus, TI CC2652P Coordinator,

### ISSUE THREAD

**Issue by nlienard** [patience4711/RPI-APS-inverters#41]
Hi
Will it work with SONOFF ZigBee 3.0 USB Dongle Plus, TI CC2652P Coordinator (it is based on  TI CC2652P + CP2102N)  ?
Or is it mandatory to use cc2530  ?
thanks

**Comment by patience4711** [comment]
@nlienard 
Thank you for your interest in this software.
Will it work with SONOFF ZigBee 3.0 USB Dongle Plus, TI CC2652P Coordinator (it is based on TI CC2652P + CP2102N) ? NO
Or is it mandatory to use cc2530 ? YES (2530 /2531)
