### ISSUE TITLE
CC2530 connection and flashing

### ISSUE THREAD

**Issue by rasor89** [patience4711/RPI-APS-inverters#43]
I tried to flash the CC2530 on Raspberry b+, but even if I tried different ways, it doesn't work. So to find the right solution, my first questions is, what is the correct GPIO connection for the CC2530? That what is stated in the readme won'T work, only ID = ffff will be shown in the console. I also tried to use the configuration from https://blog.boris-wach.de/permalink/265 but "./cc_chipid" resutlt is ID = a524 instead of ID = b524. Flashing is working, but without "verifying page 128/128." Nevertheless no connection via the PRI-ECU is working. 

> running script checkCoordinator.pl...
calling checkCoordinator.cgi command to run = sudo /usr/lib/cgi-bin/ecu/checkCoordinator.cgi
Content-type:text/html
running checkCoordinator.cgi
wiringPi started
opened port serial0
command = 00270027
no answer
no answer on serial
toLog =
01:00:46 checking zb system failed, no answer on serial
logCmd = echo "
01:00:46 checking zb system failed, no answer on serial" >> /ramdisk/ecu_log.txt
command runned
HTTP:1/1 200 OK<

**Comment by ghost** [comment]
@rasor89  Thank you for your interest in this software.
I get the idea that you are flashing z-stack on your zb module. this wont work.
Please see the readme chapter hardware. You can also find the correct wiring.

**Comment by rasor89** [comment]
@patience4712 I only used this guide for the Single steps, but used the hex files from your download.
Can you Tell me correct gpios and Pins on the CC2530 Module and how you did the flashing? Is there anything I have configurate in the raspberry in Addition? (config files or something like that?)

**Comment by ghost** [comment]
I flashed with the method of blog.boris. You should have wiring-PI updated. Otherwise i wouldn't know. Today i have no time to help you with this.

**Comment by rasor89** [comment]
@patience4712 but the connection described in Blog Boris is different from what is described in your readme. This is why I Asked what is the correct one?

**Comment by patience4711** [comment]
@rasor89 In my readme there is no reference to wiring for the purpose of flashing, only for the serial connection. 
For flashing the cc25xx i only referenced to the web where a lot is written on this subject. 

"./cc_chipid" result is ID = a524, the zb is responding so the wiring for the flashing should be oke. If the erasing and other operations are successfull, you should reconnect the cc2530 according wiring in the readme. Now it should respond to serial commands from the Rpi.

**Comment by rasor89** [comment]
@patience4712 ah ok, understand, i didn't keep in my mind, that the wiring during flashing is different from the operation. I will try and post the result. Thanks!

**Comment by rasor89** [comment]
Yeahh or works. The wiring was the mistake. Thx @patience4711
