### ISSUE TITLE
What does "inv 0 error 11 AF_DATA_CONFIRM fail" mean?

### ISSUE THREAD

**Issue by peter33826** [patience4711/RPI-APS-inverters#49]
Hi, 
what is the reason for this error message:

polled inv 0 error 11 AF_DATA_CONFIRM fail
invdataNull.cgi: set values to null except
for totalen and time in /ramdisk/invData0

Yesterday connection was fine but after sunrise i get this error code.

Thanks.

**Comment by patience4711** [comment]
You can read that [here](https://cupdf.com/document/z-stack-monitor-and-test-api.html?page=16)
In short: there has been an error in the zigbee communication. I think most of the time a range problem.  <br><br>
B.t.w. are you happy with the values that are reported?

**Comment by FloriH** [comment]
Good morning together, hello @patience4711,

i setup the 3.3 image, do the update to 3.6 and flash my cc2530 (with 2591). The uart communication looks fine (coordinator health check) and I am also able to do the pairing with my inverter (DS3-L)(I do it with distance from 25m to 5m, same result): rpiecu gets the short ID and tells „pairing successful“.
But the polling never works (Pout > 50W). I try to short the distance to 5m, but this doesn’t help.
I always get the following messages

`running script inverterPoll.pl...
argument is 0 
sudo /usr/lib/cgi-bin/ecu/inverterPoll.cgi 0 
Content-type:text/html
running inverterPoll.cgi
inverterpoll running with arg 0 
invSerial from file = [703000577307]
invType = 2 
idx = 0 
invIdrev = 1AA3 
idShort = xxxx 
idinvers from file = 80971B01B3D6 
poll cmd = 1D24011AA31414060001000F1380971B01B3D6FBFB06BB000000000000C1FEFE8E 
answer = FE0164010064FE034480CD14011F 
messageToDecode = FE0164010064FE034480CD14011F 
no AF_DATA_CONFIRM 
all cmds sent 
returned by sendCommands() 11 
toLog = 
16:28:51 polled inv 0 error 11 AF_DATA_CONFIRM fail 
logCmd = echo "
16:28:51 polled inv 0 error 11 AF_DATA_CONFIRM fail" >> /ramdisk/ecu_log.txt 
Content-type:text/html
running invdataNull.cgi
echo "{ 'time': 0, 'pwr': [ 0, 0, 0, 0 ], 'totalpw': 0, 'idx': 0, 'dcc': [ 0, 0, 0, 0 ], 'dcv': [ 0, 0, 0, 0 ], 'heath': 0, 'freq': 0, 'totalen': 0, 'acv': 0, 'en': [ 0, 0, 0, 0 ] }" > "/ramdisk/invData0" 
sedCmd = sed -i 's|['\'']|'\"'|g' /ramdisk/invData0 
invdataNull.cgi: resetted existing invData 
invdataNull.cgi exit with code 0 
inverterpoll exit with code 0 
command processed 
HTTP:1/1 200 OK`

Any idea what I’m doing wrong?

The test Zigbee loopback fails with the message: „no answer“
Is there a communication with the Inverter or is it like the eth-Loopback only inside the zigbee-module?
