### ISSUE TITLE
Sources without burning RPi Image

### ISSUE THREAD

**Issue by fellek** [patience4711/RPI-APS-inverters#52]
Hi @patience4711 , Thanks for working on this project. I would like to ask, if there is a way to share the sources at github. Creating, downloading and burning images is a very cpu-intensive way of sharing some scripts. Beneath there would be a way to work in team on this project.

Thanks for answering!

**Comment by patience4711** [comment]
It's the easiest and least labor intensive way for me. It is not a matter of just sharing some scripts you know.

**Comment by fellek** [comment]
Thanks for the straigth answer. I wonder wether there is a specific difference between the esp /raspi programs and if you have plans to share them. In my specific setup I would like to use my running raspi for polling my inverters (of course there are two DS3-S, they are not supported by version 2.7)

**Comment by patience4711** [comment]
The difference is the programming languages, in the RPI we have C++, Perl, PHP, Javascript, Bash, python, maybe i forgot one. In the ESP only Arduino C.
I think you would like a package that installs this system on an existing Raspberry. No plans for that, too complicated for me.

**Comment by fellek** [comment]
Hi @patience4711 , I see the RPi programm is much more complicated than the Arduino one. I am used to compile/ install dependencies myself, no call for installable packages. Although its reasonable not to provide all types of possible sources/packages/images at the same time.
