### ISSUE TITLE
having a new variable for totalen

### ISSUE THREAD

**Issue by nlienard** [patience4711/RPI-APS-inverters#53]
currently totalen is reseted every day and due to that, integration in Home Assistant is having troubles.

it is possible to have a variable totalen2 (or whatever) which is a total which always increments for ever ?

thanks

**Comment by patience4711** [comment]
Not possible, when this value is written to a file we would wear out our sdcard, when saved in ramdisk it would disappear at a powercycle.

**Comment by rasor89** [comment]
would it be an possible option to write down the values in an external influxdb?

**Comment by nlienard** [comment]
another question: how do you create totalen currently ? i don't see any doc explaining the raw output of the invecter.
I thought it sends the totalen as raw, as a total always incrementing but if i understand, when inverter restarts, it doesn't keep in its internal memory the previous value and began back to 0 ?

**Comment by patience4711** [comment]
totalen is the value polled from the inverter. (total of all panels). Will be reset after a inverter restart. Please read the wiki subject inverters

**Comment by patience4711** [comment]
@rasor89 If you use the http request you can write into an external database as much as you like.

**Comment by nlienard** [comment]
finaly it is not an issue if inverter restarts and put totalen to 0 because home assistant is smart and manages to correct it without any action

![image](https://user-images.githubusercontent.com/13884545/175644370-f157b0c3-195c-47e3-a677-b8201431fd54.png)

```
root@rpiecu:~# grep restart /ramdisk/ecu_log.txt
<br>18:36:04 polled inv 0 inverter restarted
root@rpiecu:~# grep -B 10 -A 10 restart /ramdisk/ecu_log.txt
<br>18:28:17 checking zb system running ok
<br>18:28:19 polled inv 0 ts: 119 pw: 82.2
<br>18:30:02 checking zb system running ok
<br>18:30:04 polled inv 0 ts: 105 pw: 78.2
<br>18:32:03 checking zb system failed, no answer on serial
<br>18:32:17 checking zb system running ok
<br>18:32:19 polled inv 0 ts: 136 pw: 73.8
<br>18:34:02 checking zb system running ok
<br>18:34:04 polled inv 0 ts: 105 pw: 72.1
<br>18:36:02 checking zb system running ok
<br>18:36:04 polled inv 0 inverter restarted <=================== RESTART HERE
<br>18:36:04 polled inv 0 ts: 88 pw: 70.9
<br>18:38:02 checking zb system running ok
<br>18:38:04 polled inv 0 error 10 AF_INCOMING_MSG fail
<br>invdataNull.cgi: set values to null except<br>for totalen and time in /ramdisk/invData0
<br>18:40:01 checking zb system running ok
<br>18:40:03 polled inv 0 ts: 239 pw: 67.3
<br>18:42:01 checking zb system running ok
<br>18:42:04 polled inv 0 ts: 120 pw: 64.3
<br>18:44:01 checking zb system running ok
<br>18:44:03 polled inv 0 ts: 120 pw: 58.9
```
