### ISSUE TITLE
manual polling

### ISSUE THREAD

**Issue by patience4711** [patience4711/RPI-APS-inverters#54]
Some of you like to poll the inverters more often. Alhough i myself consider this as completely unnecessary, and potentially dangerous for the stability of the system, i made this possible.  As of version 2_9 there is a possibility to trigger the polling manually. If you issue a request like http://ip_of_ecu/recovery/pollCmd?poll=x then the inverter x is polled. The autopolling should be disabled.

This is not fully mature as the polled data are processed the same as an automatic poll. This has some unwanted effects.
- first of all a multiple of the normal data is added to the database. This will slow down query processes and eats memory.
- the charts are not adjusted for this data 
- The autopoll does some sanity checks that are skipped when manually polled.
-  the system has no knowledge of other (previous) polls and cannot calculate with the data.

All and all i have some regrets that i made this possible.  So i have to adapt this in a way that in case of a manual poll, the data is not added to the database.  That means that there is a separate script for the manual polling needed that only communicates the polled data. No further calculations or conclusions, only that the poll failed/succeeded. So there won't be a power variable, the user has to calculate that.

Please, if you are going to use the manual polling: First make absolutely sure that the system works stable with the autopolling. So that when issues arrise we can relate them to the manual polling.

**Comment by nlienard** [comment]
thanks to have created this issue.
What is the instability to run the autopoll every 2 mn instead of 5mn ?
is it something experienced or known ? 
Do we know what is the polling rate on ECU appliance to have some reference ?

In another hand, after reading the calculation of totalen on wiki/invecters, it doesn't matter that we change the polling frequency as you calculate the shift from the timestamp between 2 polling.

**Comment by patience4711** [comment]
We know from the esp project that higher polling rates cause troubles, APS works with 5 minutes. True, for the calculations it does not matter but when values become erratical ...

For the powercalculations and database functionallity, the polling should be systematically. This way a first poll after an inverter reset (also at wake-up) can be identified, and appropriate actions can be taken.
I have been thinking of a separate manual polling script but that would mean no power calculations and it would affect the functionality of the program too much.  

So i stop putting energy in this. In future versions i'l remove the manual polling.
