### ISSUE TITLE
Version 3.3 no Totals / stats

### ISSUE THREAD

**Issue by rasor89** [patience4711/RPI-APS-inverters#59]
Hello @patience4711 

Edit: I found the reason of the failure: when i select 2 panels, everything is fine. With 1 panel it doesn't work.

after the update to version 3.3 I have no link for the stats (headbar is missing!) in the page of my converter. Also there is no "Totals" available. See below picture. All other is working (so the system is connected with the converter and current energy and power is shown during the day.
Because I wasn't sure, that the update reasoned this problem, I flashed the system complety new (3.3 img) and restored the backup. But the failure is still available. 
Furthermore I want ask, why in the info the number of users is 0?

![112022-08-07 00_57_54-RPI-ECU](https://user-images.githubusercontent.com/106281918/183268440-d9711da0-8551-4c6d-ba50-34638a8d1d70.png)

![2022-08-07 00_45_58-RPI-ECU](https://user-images.githubusercontent.com/106281918/183268237-cf6c312b-ea39-4ddb-a7b8-728eedb19932.png)

![2022-08-07 01_00_27-192 168 178 72_protected_info php](https://user-images.githubusercontent.com/106281918/183268523-6cbb2370-9e26-4bad-bcad-5f7afd113fcd.png)

**Comment by patience4711** [comment]
Sorry to hear that, When you click the button that says DS3 you should get the details page with buttons to the statistics and the charts.
So you say when there are 2 panels everything works like it should. With one panel there are no figures in the main page. I have to investigate this. I am sure that it's only a small detail.
The frontpage only shows totals when there are multiple inverters so this seems oke.

Edit: The page with the inverter details should contain a "total" row with the sum of all panels. It does not when there is only 1 panel, this is a bug. 
version 3_5 is available that should solve the problem.

The usercount is the number of logged-on users in the system, e.g. logged-on via ssh. It is not very interesting so in future versions it will be removed.

**Comment by patience4711** [comment]
No thanks...

**Comment by rasor89** [comment]
@patience4711 sorry for not replying, but didn't found time the last days for testing the new version. I went back to the 2.9 to have a working system. Maybe I will find some time in the next days.
