### ISSUE TITLE
What does "inMessage = FE0164020067" mean?

### ISSUE THREAD

**Issue by Cryss67** [patience4711/RPI-APS-inverters#60]
Hello!

I try to pair my inverter (DS3-S) on my Raspberry 3b using your v3.3 image.
Do you need any more information from me?

I've successfully copied the firmware to the Zigbee module, but on pairing I get this message and I can't figure out it's meaning.

```

running script inverterPair.pl...
argument is 0 
sudo /usr/lib/cgi-bin/ecu/inverterPair.cgi 0 
Content-type:text/html
running inverterPair.cgi

inverterpair running with arg0
wiringPi started 
opened port serial0 
fileToread = /var/www/ecu_data/ecuProperties
json from file = { 'idinvers': "80971B01A3D8", 'id': "D8A3011B9780" } 
idinvers from file = 80971B01A3D8 
ecushort = A3D8 
fileToread = /var/www/ecu_data/inverters/invProperties0
json from file = { 'panels': [ 1, 1, 0, 0 ], 'idx': "", 'id': "unpaired", 'name': "Inverter 1", 'type': 2, 'serial': 702000014595 } serial from file = 702000014595 
trying to pair inverter0 
send cmd 0 2524020FFFFFFFFFFFFFFFFF14FFFF140D0200000F1100702000014595FFFF10FFFF80971B01A3D8FA 
inMessage = FE0164020067 
send cmd 1 1A24020FFFFFFFFFFFFFFFFF14FFFF140C0201000F0600702000014595B4 
inMessage = FE0164020067 
no pairing answer, returning... 
proceeding with the next cmd 
send cmd 2 2524020FFFFFFFFFFFFFFFFF14FFFF140F0102000F1100702000014595A3D810FFFF80971B01A3D882 
decode inMessage = FE0164020067 
no pairing answer, returning... 
no pairing answer, returning... 
proceeding with the next cmd 
send cmd 3 1A24020FFFFFFFFFFFFFFFFF14FFFF14010103000F060080971B01A3D84F
decode inMessage = FE0164020067 
no pairing answer, returning... 
all pair cmds done
info = 5 
pairing failed, try again... 
inverterPair ready 
pair command processed 
HTTP:1/1 200 OK
```

Healthcheck output:

```
running script checkCoordinator.pl...
calling checkCoordinator.cgi command to run = sudo /usr/lib/cgi-bin/ecu/checkCoordinator.cgi
Content-type:text/html
running checkCoordinator.cgi

wiringPi started 
opened port serial0 
command = 00270027 
answer = FE0E670000FFFF80971B01A3D8000007090011 rc=19 
fileToread = /var/www/ecu_data/ecuProperties
idinvers from file = 80971B01A3D8 
coordinator is running ok 
toLog = 
18:31:54 checking zb system running ok 
logCmd = echo "
18:31:54 checking zb system running ok" >> /ramdisk/ecu_log.txt 
command runned
HTTP:1/1 200 OK
```

```
running script sendZigbee.pl...
argument is 2710AABBCC 
sudo /usr/lib/cgi-bin/ecu/testZigbee.cgi 2710AABBCC 
Content-type:text/html
running testZigbee.cgi

testZigbee running with arg 2710AABBCC 
wiringPi started 
command incl. FE, len and crc = FE032710AABBCCE9 
inMessage = FE036710AABBCCA9 
command processed 
HTTP:1/1 200 OK
```

**Comment by Cryss67** [comment]
So it SEEMS that it was an issue of distance. I wasn't able to pair the inverter with the Zigbee module at 1 meter, but now it worked 50 cm away. Is this possible?
What's the point of a Wifi module that needs to be that close?
Is it possible that the radio power is set is too low and needs to be adjusted?


The used Zigbee module is this:
https://www.amazon.de/gp/product/B01FXC1G5M/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1

H-2 Z-002 (TICC2530 CC2591) UART to ZigBee Module with 2.4G Antenna (max. 400m)

- CC2530 Module with CC2591, default Firmwar UART to Zigbee, deliveried with 2.4G 3dBi Antenna, max. Transmission 500m, Documentation is downloadable (H-2 Technik)
- Supporting Z-Stack2.5.1a and 3.0.2
- 3dBi Atenna included


I flashed "CC2530ZNP-with-SBL.hex". Is this correct? Or should it had been "CC2530ZNP_2591-with-SBL.hex"?


Update: Solved
The "CC2530ZNP_2591-with-SBL.hex" did the job.

**Comment by rasor89** [comment]
@Cryss67 could you increase the range? Can you test the max. possible? I'm still looking for options to increase the signal strengh, because at the moment I can only realize small distances between my RPI and the converter.

**Comment by Cryss67** [comment]
Currently, the Zigbee module is about 5 meters away from the inverter with two walls  (I guess Y-Tong) in between. I‘ll try to test the range although I need to find a mobile solution for the raspi as I live on the upper floors of a rented apartment with no power supply

**Comment by Cryss67** [comment]
BTW, what other features have you planned?
