### ISSUE TITLE
What are these inverter spikes?

### ISSUE THREAD

**Issue by Cryss67** [patience4711/RPI-APS-inverters#61]
is there a way to „normalize“ these, I guess, wrong values?

![C46BF77B-7820-46A8-918B-BAF637052EB2](https://user-images.githubusercontent.com/111450985/185860093-50d29141-f799-4ec7-a264-85cdede81c3e.png)

**Comment by patience4711** [comment]
What systemversion/inverter? They are most likely the result of a disturbed polling/zigbee communication. You can check that in the journal and in the timeline of the chart. The system ignores unrealistic values so in the end the total energy value should be oke.
If not you can change the value for that day in the energy database.

**Comment by Cryss67** [comment]
Software version: RPI-ECU-v3_5
The inverter is a DS3-S.

Thanks for your help!
