### ISSUE TITLE
test zigee module

### ISSUE THREAD

**Issue by defaliz** [patience4711/RPI-APS-inverters#64]
Hi, thank a lot for your work
i test my zigbbe module with the command /usr/lib/cgi-bin/ecu/testZigbee.cgi 2710AABBCC
the return is 
<br>
wiringPi started
<br>
command incl. FE, len and crc = FE032710AABBCCE9
<br>
inMessage = FE036710AABBCCA9

but not this line :
HTTP:1/1 200 OK (like it's written in the wiki)

when i inverse TX and RX i 've "no answer"
is that mean my module is OK when nothin is display in the console ?
regards

**Comment by defaliz** [comment]
ok that's work in the web console...
the response "http..." is not visible in the raspberry console..

**Comment by patience4711** [comment]
The inmessage is correct so the zigbee is working.
