### ISSUE TITLE
change some aps parameters ?

### ISSUE THREAD

**Issue by defaliz** [patience4711/RPI-APS-inverters#65]
Hi,
i'm using this great program..
thank patience4711
do you think if there is a possibility to change some parameter of aps device ?
like stop one solar panel, or other things...
regards

**Comment by patience4711** [comment]
In theory this is possible, when someone sniffs the zigbee traffic we could analyze it. This was already asked before,

**Comment by defaliz** [comment]
Ok, thanks for your quick reply..
Regards
