### ISSUE TITLE
Feature Request - separate values for 2 modules

### ISSUE THREAD

**Issue by peter33826** [patience4711/RPI-APS-inverters#66]
Is it possible that with a DS3 with 2 modules the values
(1) module 1
(2) module 2
(3) sum of modules 1+2
be displayed in the diagram?

(3) Is already implemented. (1) and (2) would be great in a future version.

Thanks.

**Comment by Hansiart2** [comment]
Sorry but no, this would mean a much larger database which would slow down all queries too much. This is not desireable. If you want that you can use the mosquitto signals and domotica software f.i. domoticz.or thingspeak.
