### ISSUE TITLE
are my value OK with 2 solar panels ?

### ISSUE THREAD

**Issue by defaliz** [patience4711/RPI-APS-inverters#69]
Hi,
i've 2 solar panels with 320 Wc and 30V 10A connected on a aps ds3 L microcontroler
but with rpiecu i've only 35 V max and 50 % of power..
now i've 17,5 W and with a my solar outer i've double value : 35 W
do you know why, it seems that rpiecu see only one panel...

![image](https://user-images.githubusercontent.com/41428343/192245828-3f9b5d32-efd6-4c26-8af3-0e7c0c8ae8f3.png)

thanks

**Comment by patience4711** [comment]
You should check the inverter page, looks like you checked only one panel there.

**Comment by defaliz** [comment]
thank a lot Patience...
exact, i've checked box 2 but it must be checked box 1 AND 2...
it's better now..
regards
