### ISSUE TITLE
Raspberry Pi 1 Mod. B support

### ISSUE THREAD

**Issue by hansnull** [patience4711/RPI-APS-inverters#7]
Hi,

I would like to run your image on a Raspberry Pi 1 Mod. B without WLAN. Your image boots up, but I cannot login and switch your scripts to a wired LAN.
First of all I need a username and a password to login. Furthermore it would be helpful to find the "entrypoint" of your implementation.

Any help appreciated : )

**Comment by patience4711** [comment]
if you mean the ssh login, its root and mies
Entrypoint?? As far as i know you only have the get the serial port working, someone has tried that already without luck.

**Comment by hansnull** [comment]
Ok, thank you, I will buy a zero then.
