### ISSUE TITLE
Firmware version of the inverter ?

### ISSUE THREAD

**Issue by nlienard** [patience4711/RPI-APS-inverters#70]
Hi

Is it possible to get the Firmware version of the inverter (in my case DS3L). ? ex 1.2.23 

![image](https://user-images.githubusercontent.com/13884545/192528124-e56e1008-9b6e-442a-bd8e-84343a485ed2.png)

Thanks !

**Comment by patience4711** [comment]
If you can find the corresponding zigbee command the answer maybe yes. You can issue that command (if it exists) via the console. Maybe you can ask one of the guys [here](https://github.com/Koenkk/zigbee2mqtt/issues/4221)<br>I cannot find it. 
Good luck..

**Comment by patience4711** [comment]
Looks like someone is able to get the firmware version, check this:
https://gitlab.com/moreroid/apsystems/-/blob/main/firmware/apsystems-firmware-download.sh


# 000-104: len 105: APsystems DS3-S ZigBee af_data_request poll response

# 000-005: len 06: 0x70 0x20 0x00 0xaa 0xbb 0xcc : inverter serial number
# 006-007: len 02: 0xfb 0xfb           : tagstart
# 008-008: len 01: 0x5c                : datalen without crc data
# 009-010: len 02: 0xbb 0xbb           : static09
# 011-011: len 01: 0x20                : version_patch?
# 012-012: len 01: 0x00                : static12
# 013-013: len 01: 0x02                : version_minor?
# 014-014: len 01: 0x01                : version_major?
# 015-021: len 07: 0x0f 0xff 0xff 0x00 0x00 0x00 0x00 : static15
# 022-022: len 01: 0x00                : unk22 - 0x00 (default), 0x01 (overload?), 0x80 (startup?)
# 023-023: len 01: 0x00                : unk23 - 0x00 (default), 0x,02 (???), 0x40 (short after startup)
# 024-024: len 01: 0x00                : unk24 - 0x00 (default), 0x0a (startup/shutdown?), 0x20 (DC1 missing), 0x80 (DC2 missing), 0xaa (no power?)
# 025-025: len 01: 0x00                : unk25 - 0x00 (default), 0xaa (startup/shutdown?)
# 026-027: len 02: 0x07 0xcf           : DC1 voltage - V (raw / 48) confirm by measurement
# 028-029: len 02: 0x01 0x96           : DC2 voltage - V (raw / 48) confirm by measurement
# 030-031: len 02: 0x00 0xb3           : DC1 current - A (raw / 80) confirm by measurement
# 032-033: len 02: 0x00 0x01           : DC2 current - A (raw / 80) confirm by measurement
# 034-035: len 02: 0x03 0x75           : AC Voltage  - V (raw / 3.75?)
# 036-037: len 02: 0x13 0x87           : AC Freq - Hz (raw / 100)
# 038-039: len 02: 0x4f 0xc8           : uptime - seconds (counter reset after 43200 will reset DC* energy also)
# 040-041: len 02: 0x00 0x4b           : AC power : W (max seen 651 W)
# 042-043: len 02: 0x00 0x30           : DC mppt? (seen 24 - 66)
# 044-045: len 02: 0xff 0xff           : static44
# 046-047: len 02: 0x05 0x36           : unk46 - 0x0021 (at starting), 0x055a (max seen), 0x02fc (ending)
# 048-049: len 02: 0x08 0xd5           : temperature - °C  (raw / 100?)
# 050-053: len 04: 0x01 0x27 0x67 0xae : DC1 energy - Wh (raw / 65535)
# 054-057: len 04: 0x00 0x00 0x58 0x1b : DC2 energy - Wh (raw / 65535)
# 058-058: len 01: 0x00                : unk58 - 0x00 (both panel power generate), 0x02 (overload?), 0x03 (no power generate), 0x04 (???), 0x05 (only DC2 power generate), 0x06 (only DC1 power generate), 0x0b (boot up?), 0x0c (boot up?)
# 059-100: len 42: 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff : static59
# 101-102: len 02: 0x38 0x3c           : CRC?
# 103-104: len 02: 0xfe 0xfe           : tagend

**Comment by nlienard** [comment]
yes, the link about it is this one i guess : 
https://gitlab.com/moreroid/apsystems/-/blob/main/zigbee/apsystems-zigbee-ds3-poll.txt
the one you mentionned is about firmware update ?

**Comment by Cryss67** [comment]
Great!

BTW, are the changelogs for firmware changes (DS3-S) to be found somewhere or have I overlooked them?

**Comment by mi-hol** [comment]
> are the changelogs for firmware changes (DS3-S) to be found somewhere or have I overlooked them?

Apsystems does NOT seem to publish changelogs for firmware

**Comment by nlienard** [comment]
anyone is able to interpet the previous post with hexa code to have a proper zigbee command to send to the inverter for having Firmware version ? thanks

**Comment by defaliz** [comment]
Bonsoir Nicolas
j'ai de gros problèmes pour apairer zigbee et mon APS ds3L
à quelle distance faut-il être du micro onduleur ? j'utilise un raspberry
merci pour votre réponse
Alain

**Comment by nlienard** [comment]
@defaliz j'ai eu pas mal de souci aussi avec la portée, je dirais qu'il faut être à moins de 5m si y a trop d'obstacles.
j'ai acheté une antenne avec une rallonge filaire pour rapprocher l'antenne le plus possible de mon DS3L. c'est désormais près de la fenêtre et le signal est mieux et j'ai plus de pb.

**Comment by defaliz** [comment]
Merci Nicolas
j'ai remarqué également qu'avec un mur en brique entre les 2, 5m c'est le max..
tu as mis ton antenne sur un raspberry pi ou zero ?

**Comment by nlienard** [comment]
sur un rpi3B+

**Comment by defaliz** [comment]
merci tu as un lien qui montrerai le montage ? j'ai rien trouvé..
merci encore

**Comment by nlienard** [comment]
a la fin de ce post https://github.com/patience4711/RPI-APS-inverters/issues/42#issuecomment-1155443357 , j'ai mis le schéma de montage que j'utilise et qui fonctionne.

**Comment by defaliz** [comment]
Merci beaucoup, je regarde ça
bonne soirée
