### ISSUE TITLE
V 2_1 to V2_7 and more

### ISSUE THREAD

**Issue by Chen32220** [patience4711/RPI-APS-inverters#74]
Hello,
i am in V2_1 and i could update to 2-7 for 3. an more.
How to do?
Best regards

**Comment by patience4711** [comment]
You are far behind. I think it is best to burn the latest sd-card image. If you can backup your database you can restore it to your new system.
Please read [here](https://github.com/patience4711/RPI-APS-inverters/wiki/SOFTWARE-UPGRADE#new-sd-card-image)
