### ISSUE TITLE
Any chance that it would work on ATmega256RFR2 ?

### ISSUE THREAD

**Issue by leola** [patience4711/RPI-APS-inverters#75]
Hello 
Thanks for this software, therefore I have a RaspBee based on ATmega256RFR2 (deRFmega256-23M12)
https://cdn.webshopapp.com/shops/53093/files/260924900/datasheet-raspbee.pdf
Would it be very different than CC2530 ? 

Thanks for the help

**Comment by patience4711** [comment]
Won't work. The cc2530 has special firmware for this project.
