### ISSUE TITLE
Where are log for testing power reception signal ?

### ISSUE THREAD

**Issue by defaliz** [patience4711/RPI-APS-inverters#76]
Hi all,"
i've some difficulty to pairing my aps with rpi ecu, where can i see the log ? 
in the wiki it's saying  : "In the journal you can see if polling failed. Also you see the signal quality"

where is the journal ?
regards
Alain

**Comment by defaliz** [comment]
OK i've seen the journal, it's in the info menu..
but nothing about zigbee signal ..

invdataNull.cgi: wrote a new /ramdisk/invData0 with null values
invdataNull.cgi: wrote a new /ramdisk/invData1 with null values
19:19:00 checking zb system running ok
19:24:01 checking zb system running ok

**Comment by patience4711** [comment]
The signal quality data is provided within the polling answer. No pairing, no polling no signalquality.

**Comment by defaliz** [comment]
thank you for reply
did rpiecu is connected to ECU during sleep time ? and what is the good distance between APS and zigbee ?
because i can't pair anymore...

no pairing answer, returning...
no pairing answer, returning...
proceeding with the next cmd
send cmd 3 1A24020FFFFFFFFFFFFFFFFF14FFFF14010103000F060080971B01A3D84F
decode inMessage = FE0164020067
no pairing answer, returning...
all pair cmds done
info = 5
pairing failed, try again...
inverterPair ready
pair command processed
HTTP:1/1 200 OK

**Comment by patience4711** [comment]
Impossible to say what a good distance is, depends on local circumstances, harware, etc. You can try to change the ecu id and try again.

**Comment by defaliz** [comment]
i've succeeded pairing my APS... distance from zigbee is about 5m for me..
thanks
regards
