### ISSUE TITLE
utility of grafana server on rpiecu ?

### ISSUE THREAD

**Issue by defaliz** [patience4711/RPI-APS-inverters#78]
Hi Hans,
i've seen grafana starting with systemctl on rpiecu image..
is it useful ? can i stop it ?
regards
Alain

**Comment by patience4711** [comment]
Hi Alain, i can't find grafana running om my system. You should be able to reach it on port 3000 but that fails.  So i tried:
_/bin/systemctl disable grafana-server_ and _~# /bin/systemctl stop grafana-server_
I get: Failed to stop grafana-server.service: Unit grafana-server.service not loaded.
So yes i think you can stop it when running, i can't remember that i installed it but it seems it was not properly un-installed. 
Good luck...
