### ISSUE TITLE
Error in power calculation?

### ISSUE THREAD

**Issue by peter33826** [patience4711/RPI-APS-inverters#83]
Attached a screenshot of my device. It works great, Thanks a lot for this. But maybe there is an error in power calculation:
40,9V x 4,2A is not 124,9 W
32,8V x 2,3A is not 90,1 W

![2023-03-01 15_22_38-RPI-ECU – Mozilla Firefox](https://user-images.githubusercontent.com/45110031/222265463-141a1196-03d6-4ba9-a9fb-7f6c4981af65.png)

Thanks for any ideas.

**Comment by patience4711** [comment]
The polling has a frquency of once in 5 minutes. The calculation of some values can be found in the wiki (subject polling). It is obvious that you can't use the u*i formula since these are momentary values that fluctuate a lot within 5 minutes.

**Comment by peter33826** [comment]
I expected a 5 min (moving) average for U and I and then calculation of P. Thank you for the explanation.
