### ISSUE TITLE
How install from file and not sd card

### ISSUE THREAD

**Issue by zasquash** [patience4711/RPI-APS-inverters#87]
hello

I want to integrate your work on an armbian (nanopi neo lts with Sonoff cc2531).
How can I install from git sources?

best regards
JABa

**Comment by patience4711** [comment]
@zasquash That is not easy to explain. I would have to study a nanopi first.
You have the image so you can extract all the scripts and c programs (cgi-bin)  and webfiles (var/www). You should have an Apache webserver running and reflash the sonoff with the relative firmware. Copy crontab. Setup ramdisk.
Not sure if this will work. The pins are different so the scripts have to be adapted to that.
Good luck ...
