### ISSUE TITLE
Problems with HTTP Request

### ISSUE THREAD

**Issue by HackTheMac** [patience4711/RPI-APS-inverters#88]
Wehen using the HTTP Request to retrieve date, e.g. http://rpiecu/recovery/getInverter.php?inv=1, the JSON is not directly returned. Rather there is some header, e.g. the header tag before the JSON which makes processing rather inconvenient.

**Comment by patience4711** [comment]
Thank you for your interest in my software. What version are you running? Are you new to this software? Are you able to login on the rpi and edit files? What browser do you use?

I really can't understand what you get, but I get this (as intended) with Chrome and Edge: 

![json](https://github.com/patience4711/RPI-APS-inverters/assets/12282915/a4f86c95-f257-4cf5-8b47-442f7fba2df4)

This is a copy of the file invData0 in ramdisk. If that file is corrupt, the webinterface wouldn't show values. 

If you can edit /var/www/html/recovery/getInverter.php you could add `</body></html>` at the end, maybe that helps.

**Comment by HackTheMac** [comment]
Hi patientce4711,
no, I am not new to your software. I have been using it for some time and I am very impressed by what you are delivering.
I am capable of logging into the rpi and edit files. I am sorry I am not good with GitHub that is probably why you are not getting my issue. I fully agree that when calling getInverter.php a perfectly fine looking json string shows up in the browser. However, if you take a look of the source code of said displayed page you will note that there is more than just the json string. As previously mentioned, there is a header tag prior to the string.

I just looked at getInverter.php:
![image](https://github.com/patience4711/RPI-APS-inverters/assets/138353616/573466f5-d95c-4555-a411-029a90d8aa6a)
While I am not good with PHP, I would assume that the first three lines is what is causing my issue. 

This is not severe. I just wanted to give you some feedback.

**Comment by patience4711** [comment]
Yes, if you ask for the page source you get  the page source. That is normal html. However, you can remove the html part so that it starts with `<?php` en ends with `?>` 
Then the page source is only the echoed json.  Or, when there is no data, you get an error message
