### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by HackTheMac** [patience4711/RPI-APS-inverters#89]
I am new to githup and unsure whether feature requests should be submitted as issues. Thus, if I am doing something wrong please let me know and I will close down the issue. 

I was just wandering whether adding further functionality for controlling the inverters is on the road map of development. I read somewhere that there are software commands to put one or all of the inverters into a maintenance mode in which no electricity will be produced. Further, I am looking for the feature to limit the output of an apsystems DS3-L inverter to 600 Watt so that it is in conformity with current German law.
Best regards

**Comment by patience4711** [comment]
@HackTheMac You are not the only one. But forthat we need someone who has an official ecu and is able to sniff the relative zigbee commands so that we can analyze that. I waited a long time for such a volunteer....
So.. sadly no plans for that.

**Comment by HackTheMac** [comment]
Can it be that the price for the ecu dropped to 49 Euro? Is the the ECU-B the right device?
