### ISSUE TITLE
install a new wireless interface

### ISSUE THREAD

**Issue by defaliz** [patience4711/RPI-APS-inverters#90]
Hello,
i need to install a new wireless interface on my pizero rpi ecu...
the device is AWUS036NHA from alpha network
but it doesnt recognize at all...
is ther something special in the sd card image which could block the installation of this device ?
thank for reply
Alain

**Comment by patience4711** [comment]
I don't think so. But i never bothered about that, the software is for a raspberry zero W. I really don't know how to make it work with another wifi dongle. Sorry i can't help you here.

**Comment by defaliz** [comment]
Thank for your reply... I'll try other thing..
Regards
