### ISSUE TITLE
dont start anymore after filesystem resize

### ISSUE THREAD

**Issue by pvtex** [patience4711/RPI-APS-inverters#91]
Hello,

i have installed the 3.3 image on my zero w.
I resized the the filesystem and rebooted the zero.
but the resized fs size is still not shown, there is the message that you have to restart one more time.

ok i restart the system and the system cant find the partition anymore:
![image](https://github.com/patience4711/RPI-APS-inverters/assets/145853865/eff21120-6029-428e-bfd2-1d50275976ba)

**Comment by patience4711** [comment]
Don't know what the problem is, bad card or too large maybe? What you could try is install the image, and use raspi-config to resize.
