### ISSUE TITLE
Timezone note working for manual value

### ISSUE THREAD

**Issue by autourdupc** [patience4711/RPI-APS-inverters#97]
Hello.

For France, none of the predefined timezone are correct.
I need to enter Paris, so according to wiki, it should be Europe/Paris

When I manually enter Europe/Paris, it seem not working and I do not get the correct sunset / sunrise values.

Actually, in France, we are at GMT+2, and none of the predefined settings match GMT+2.

I'm running RPI-ECU-v3_3 updated to 3.8
Any help.

**Comment by ghost** [comment]
I thought that in eu we have the same time, Amsterdam, Paris, Berlin all the same. Choose from the dropdown list and it should be oke.

**Comment by autourdupc** [comment]
Well...
I did the tricks via ssh and apply the correct time zone in the system.
